-- ============================================================
-- Project     : RetailPulse Customer Behaviour Analysis
-- Description : Business questions answered 
-- ============================================================

-- Quick sanity check: preview first 20 rows before analysis
create database customer_behaviour;
use customer_behaviour;
select * from customer limit 20; 
 
 -- Q1. What is the total revenue generated by male vs. female customers?
 select gender, sum(purchase_amount) as revenue
 from customer
 group by gender; 
 
-- Q2. Which customers used a discount but still spent more than the average purchase amount?
-- Subquery recalculates avg across the full table, not just discounted rows,
-- ensuring the benchmark reflects overall spending behaviour
select customer_id, purchase_amount
from customer
where discount_applied = 'yes' and purchase_amount >= (select avg(purchase_amount) from customer); 

-- Q3. Which are the top 5 products with the highest average review rating?
select item_purchased, round(avg(review_rating),2) as 'Average product rating'
from customer
group by item_purchased
order by avg(review_rating) desc
limit 5; 

-- Q4. Compare the average Purchase Amounts between Standard and Express Shipping.
select shipping_type, avg(purchase_amount)  
from customer
where shipping_type in ('Standard','Express')
group by shipping_type; 

-- Q5. Do subscribed customers spend more? 
-- Compare average spend and total revenue between subscribers and non-subscribers.
select avg(purchase_amount) as 'average_spend' , sum(purchase_amount) as 'total_revenue', subscription_status, 
count(customer_id) as "total_customers"
from customer
group by subscription_status
order by total_revenue, average_spend desc; 

-- Q6. Which 5 products have the highest percentage of purchases with discounts applied?
select item_purchased, 
round(sum(case when discount_applied = 'Yes' then 1 else 0 end)/ count(*)* 100, 2) as discount_rate
from customer
group by item_purchased 
order by discount_rate desc
limit 5; 

/* 
CASE WHEN...: Identifies discounted rows.
THEN 1 ELSE 0: Flags matches with one.
SUM(...): Counts total flagged rows.
COUNT(*): Counts all table rows.
/ COUNT(*): Calculates the decimal ratio.
* 100: Converts to a percentage.

*/ 
-- Q7. Segment customers into New, Returning, and Loyal based on their total number of previous purchases, 
-- and show the count of each segment.
-- Thresholds: New = 1 purchase | Returning = 2–10 | Loyal = 11+
-- Adjust these cutoffs to match your business definition of loyalty

with customer_type as (                         -- WITH clause creates a temporary table called customer_type a CTE (Common Table Expression)
select customer_id, previous_purchases,
CASE 
    WHEN previous_purchases= 1 THEN 'New'
	WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
    ELSE 'Loyal'
END AS customer_segment
 from customer
 )
 select customer_segment, count(*) as 'Number of Customers'
 from customer_type
 group by customer_segment; 
  
-- Q8. What are the top 3 most purchased products within each category?
-- ROW_NUMBER() is used instead of RANK() to guarantee exactly 3 rows per category.
-- RANK() would return tied rows, potentially exceeding 3 results per category.

with item_counts as (
select category,
item_purchased,
COUNT(customer_id) as total_orders,
ROW_NUMBER() over (partition by category order by count(customer_id) DESC) as item_rank
from customer
group by category, item_purchased
)

select item_rank, category, item_purchased, total_orders
from item_counts
where item_rank <= 3;

-- Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
-- Threshold of 5+ purchases used to define 'repeat buyer'
select count(customer_id) as repeat_buyers, subscription_status
from customer 
where previous_purchases >= 5 
group by subscription_status

-- Q10. What is the revenue contribution of each age group?
select age_group, sum(purchase_amount) as revenue_contribution 
from customer
group by age_group
order by revenue_contribution desc; 



